application: winged-odyssey-4
version: 1
runtime: python27
api_version: 1
threadsafe: true



# jinja2 wsgi app lives in only dynamic handler, controlling routing
# static resources are used to deliver css, images, js
handlers:

# statics
- url: '/images'
  static_dir: static/images
- url: '/css'
  static_dir: static/css
- url: '/js'
  static_dir: static/js
  
# mapreduce stuff
- url: /_ah/pipeline.*
  script: mapreduce.lib.pipeline.handlers._APP
  login: admin
  
# endpoints
- url: /_ah/spi/.*
  script: schedulrApp.web.api.application

# webapp2 route handlers
- url: /.*
  script: schedulrApp.web.handlers.application
  


includes:
- mapreduce/include.yaml
  
  

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name: pycrypto
  version: latest
- name: endpoints
  version: 1.0